version: '3.5'

volumes:
  iso-registry-dev:

services:
  registry:
    image: registry:latest
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - iso-registry-dev:/var/lib/registry
